apiVersion: v1
kind: Pod
metadata:
  name: my-readiness-test
spec:
  containers:
  - name: readiness
    image: nginx:latest
    readinessProbe:
            httpGet:
                path: /
                port: 80
            successThreshold: 3   
