apiVersion: v1
kind: Pod
metadata:
  labels:
    test: startup
  name: startup-exec
spec:
  containers:
  - name: startup
    image: registry.k8s.io/busybox
    args:
    - /bin/sh
    - -c
    - sleep 300
    startupProbe:
      exec:
        command:
        - cat
        - /etc/hostname
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 1
