apiVersion: v1
kind: Pod
metadata:
    name: node-selector
    labels:
      app: my-app
      type: frontend

spec:
  nodeSelector:
    special: "true"      
 
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80


    #kubectl label nodes worker-node-1 special=true