apiVersion: v1
kind: Pod
metadata:
  name: my-resource-test
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      requests:
        memory: "128Mi"
        cpu: "5000m"
    ports:
      - containerPort: 80
