apiVersion: v1
kind: Pod
metadata: 
  name: vol-map
spec: 
  containers: 
  - name: my-app
    image: busybox
    command: ['sh', '-c', 'while true; do sleep 3600; done']

    volumeMounts:
    - name: configmap-volume
      mountPath: /etc/config/configmap
    - name: secret-volume
      mountPath: /etc/config/secret

  volumes:
  - name: configmap-volume
    configMap:
      name: my-configmap
  - name: secret-volume
    secret:
      secretName: my-secret
