apiVersion: v1
kind: Pod
metadata:
        name: onfailure
spec:
        restartPolicy: OnFailure
        containers:
                - name: busybox
                  image: busybox
                  command: ['sh', '-c', 'sleep 10: This is wrong format']   // correct format:  command: ['sh', '-c', 'sleep 10’]